"""Add knowledge base and AI project settings

Revision ID: 2b1489278bc6
Revises: a6c67fccd787
Create Date: 2025-08-05 12:13:01.742279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1489278bc6'
down_revision: Union[str, Sequence[str], None] = 'a6c67fccd787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the new knowledge_base_documents table
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_name')
    )
    
    # Add the new columns to the rfp_projects table
    op.add_column('rfp_projects', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('rfp_projects', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('rfp_projects', sa.Column('context_amount', sa.Integer(), nullable=True))
    op.add_column('rfp_projects', sa.Column('context_size', sa.String(), nullable=True))

    # --- Backfill commands are placed here, after columns are created ---
    op.execute("UPDATE rfp_projects SET model_name = 'gpt-3.5-turbo' WHERE model_name IS NULL")
    op.execute("UPDATE rfp_projects SET temperature = 0.2 WHERE temperature IS NULL")
    op.execute("UPDATE rfp_projects SET context_amount = 15 WHERE context_amount IS NULL")
    op.execute("UPDATE rfp_projects SET context_size = 'medium' WHERE context_size IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the columns from the rfp_projects table
    op.drop_column('rfp_projects', 'context_size')
    op.drop_column('rfp_projects', 'context_amount')
    op.drop_column('rfp_projects', 'temperature')
    op.drop_column('rfp_projects', 'model_name')
    
    # Drop the knowledge_base_documents table
    op.drop_table('knowledge_base_documents')
    
    # ### end Alembic commands ###