"""Create rfp_projects table

Revision ID: 4ea35e88905d
Revises: 
Create Date: 2025-07-21 10:55:04.508128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea35e88905d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfp_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfp_projects_id'), 'rfp_projects', ['id'], unique=False)
    op.create_index(op.f('ix_rfp_projects_name'), 'rfp_projects', ['name'], unique=False)
    op.create_index(op.f('ix_rfp_projects_project_id'), 'rfp_projects', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfp_projects_project_id'), table_name='rfp_projects')
    op.drop_index(op.f('ix_rfp_projects_name'), table_name='rfp_projects')
    op.drop_index(op.f('ix_rfp_projects_id'), table_name='rfp_projects')
    op.drop_table('rfp_projects')
    # ### end Alembic commands ###
