"""Remove obsolete context_amount column

Revision ID: 64bc8e2515ef
Revises: 2b1489278bc6
Create Date: 2025-08-06 10:31:12.221722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bc8e2515ef'
down_revision: Union[str, Sequence[str], None] = '2b1489278bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfp_projects', 'context_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfp_projects', sa.Column('context_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
