"""Add prompt_functions table

Revision ID: fc4e73cc4783
Revises: 35151fddc5b7
Create Date: 2025-07-24 15:18:33.584033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4e73cc4783'
down_revision: Union[str, Sequence[str], None] = '35151fddc5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('function_name', sa.String(), nullable=True),
    sa.Column('button_label', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function_name')
    )
    op.create_index(op.f('ix_prompt_functions_id'), 'prompt_functions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_functions_module_name'), 'prompt_functions', ['module_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_functions_module_name'), table_name='prompt_functions')
    op.drop_index(op.f('ix_prompt_functions_id'), table_name='prompt_functions')
    op.drop_table('prompt_functions')
    # ### end Alembic commands ###
